### ISSUE TITLE
TypeScript: Property '$recaptcha' does not exist

### ISSUE THREAD

**Issue by VictorKrasnov** [nuxt-community/recaptcha-module#109]
TS2339: Property '$recaptcha' does not exist on type 'LoginPopupComponent'.
    60 |   async mounted () {
    61 |     try {
  > 62 |       await this.$recaptcha.init()
       |                  ^^^^^^^^^^
    63 |     } catch (e) {
    64 |       console.log(e)
    65 |     }

**Comment by dloranc** [comment]
To solve this issue you have to add `@nuxtjs/recaptcha` to the `types` array in your `tsconfig.json`:

```
"types": [
  "@nuxtjs/recaptcha"
]
```
