### ISSUE TITLE
There was a problem initializing recaptcha/api.js on v3

### ISSUE THREAD

**Issue by tanfangping** [nuxt-community/recaptcha-module#11]
I'm using V3 key，When I started the project and looked at the loaded recaptcha/api.js, I found that the JS was missing the render parameter value, and then I printed the value in the dependency and found that in the init method, this. siteKey was valuable, but There is no value after using the string template
Init method in plugin. JS in source code：
`
 init () {

    console.log(this.siteKey) 

    console.log(src.concat(`?render=${this.siteKey}`))

    ......
    scriptElement.setAttribute('src', this.version === 2 ? src : src.concat(`?render=${this.siteKey}`))
    .....
`

Print the result after project start as follows：
6Ldyo6AUAAA......
https://www.google.com/recaptcha/api.js?render=

Q:Is this because my project does not support es6? But I have no problem writing this string template in my own project, or do I need to configure something extra to support your third-party package as well as string template?

**Comment by mvrlin** [comment]
Hello, can you provide your `nuxt.config.js` file?

**Comment by tanfangping** [comment]
> Hello, can you provide your `nuxt.config.js` file?

I deleted some useless configurations：
`module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    htmlAttrs: {
      lang: 'en'
    },
    meta: [
      {charset: 'utf-8'},
      {name: 'viewport', content: 'width=device-width, initial-scale=1'},
      {name: 'google-site-verification',content: 'wes4m4-ygaZVQkNKmj4w0BLK0FXGGW6UbsN9iB7jm28'},
      {'http-equiv': 'X-UA-Compatible', content: 'IE=edge,Chrome=1'},
    ],
    script: [
      {src: '/js/velocity.min.js', type: 'text/javascript'}
      ]
  },
 
  /*
  ** Build configuration
  */
  build: {
    extend(config, {isDev, isClient}) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        });
      }
      config.module.rules.forEach((rule) => {
        if(rule.test.toString() === '/\\.(png|jpe?g|gif|svg)$/'){
          rule.options={
            limit: 10000, name: 'img/[name].[hash:7].[ext]'
          }
        }
      });
    },
    vendor: ['swiper','axios', 'vee-validate','vue-piczoom']
  },
  modules: [
    **['@nuxtjs/recaptcha', {
      version: 3,
      hideBadge: false,
      siteKey: "6Ldyo6AU......"
    }],**
    //Simple usage
    ['@nuxtjs/google-analytics', {
      id: 'UA-96192306-5',
      autoTracking: {
        pageviewOnLoad: false
      },
      debug: {
        sendHitTask: process.env.NODE_ENV === 'production'
      }
    }],
    '@nuxtjs/axios'
  ],
  router: {
    middleware: ['auth']
  }
}

`

**Comment by tanfangping** [comment]
> Hello, can you provide your `nuxt.config.js` file?

My solution is to add a label under the script attribute: {src:'https://www.google.com/recaptcha/api.js?Render=6Ldyo6A...'} to reload a script label with render value, but this method is obviously not very good.

**Comment by mvrlin** [comment]
Try this:

```javascript
mounted () {
  console.log(this.$recaptcha.siteKey)
}
``

**Comment by tanfangping** [comment]
> Try this:
> 
> ```js
> mounted () {
>   console.log(this.$recaptcha.siteKey)
> }
> ```
The following code I wrote on my registration page：
 async mounted() {
      await this.$recaptcha.init()
      console.log(this.$recaptcha.siteKey)
    }
The result is：6Ldyo6A......
That's no problem，And script tags still don't have render values

**Comment by tanfangping** [comment]
> Try this:
> 
> ```js
> mounted () {
>   console.log(this.$recaptcha.siteKey)
> }
> ```

I tried to modify your source code as follows：
`
 // scriptElement.setAttribute('src', this.version === 2 ? src : src.concat(`?render=${this.siteKey}`))
    console.log(this.siteKey)
    scriptElement.setAttribute('src', this.version === 2 ? src : src.concat(`?render=6Ldyo6AUAA......`))
`
I commented on your first line of code.
Result: The value for siteKey is printed out correctly and The program works fine.So I think it should be a string template problem

**Comment by tanfangping** [comment]
> Try this:
> 
> ```js
> mounted () {
>   console.log(this.$recaptcha.siteKey)
> }
> ```
![image](https://user-images.githubusercontent.com/37611218/57205626-73f95680-6ff2-11e9-92b2-3e6b59e90579.png)

I found out that there is no node_module folder after install your project

**Comment by mvrlin** [comment]
@tanfangping sorry for late response. Try that in the `plugin.js`

```javascript
script.setAttribute('src', this.version === 2 ? API_URL : API_URL + 'render?=' + this.siteKey)
```

**Comment by ricardogobbosouza** [comment]
@mvrlin can closed?
