### ISSUE TITLE
*** recaptcha won't show up if re-visit the same page.

### ISSUE THREAD

**Issue by whattocode** [nuxt-community/recaptcha-module#12]
hi community,

The recaptcha-module has an issue, "recaptcha won't show up if re-visit the same page". My app is an universal application, route from landing page to the page with recaptcha it shows, and then route to landing page and go back to the page with recapcha, but the recapcha won't shown up. 
I have to refresh the page then it shows. 

Even I tried to code only the component in the template, still same happens, like this:

```
      <template>
           <div>
          <recaptcha />
        </div>
       </template>
```

 Please help!!

this is my settings in nuxt.config.js
```
['@nuxtjs/recaptcha', {
      hideBadge: false,
      siteKey: process.env.CAPTCHA_SITE_KEY, 
      version: 2,
    }],
```

I'm using the latest version of the recapcha-module v0.3.3.

**Comment by VarghaSabee** [comment]
This issue also opened before in #10  **Captcha renders only once (v2)**. I have the same problem :(

**Comment by mvrlin** [comment]
Hey! Fixed that in the release. Check it out!

**Comment by VarghaSabee** [comment]
Thx :)  the bug is fixed!

**Comment by whattocode** [comment]
Great! Thank you so much!!!

I've tested. it works like a charm. :)

**Comment by larrykkk** [comment]
I think I meet this issue in version 0.6.1 

```js
// layouts/default.vue
<template>
  <div>
    ...
    <nuxt :key="$route.fullPath"/>
    ...
  </div>
</template>
```
work for me
