### ISSUE TITLE
Failed to get response token from $recaptcha.getResponse()

### ISSUE THREAD

**Issue by ramammurshal** [nuxt-community/recaptcha-module#124]
Hi! I just try to get the response token using this function:

```js
try {
	const token = await this.$recatpcha.getResponse()
	console.log(`Token: ${token}`)
} catch (error) {
	this.$catchError(error)
}
```

But, the token log is null

My site key is already correct, it show an image validations like normal

I'm using nuxt 2, with node js version 14.5, and nuxt recaptcha version 1.1.2

How about this?

**Comment by leogenot** [comment]
How did you fix it? @kakashisenpai1
