### ISSUE TITLE
document is not defined error

### ISSUE THREAD

**Issue by bongjinpark1** [nuxt-community/recaptcha-module#13]
```vue
<v-input :error-messages="recaptchaErrors">
          <no-ssr>
            <recaptcha @error="onError" />
          </no-ssr>
        </v-input>
```

Hello. I'm using recaptcha in form and it works good.

but, document is not defined error occured when I refresh the page or I connect directly the path.

no-ssr component is not working.

```javascript
function(req, res, next) {
  const paths = ['/recaptcha-form-path']
  if (paths.includes(req.originalUrl)) res.spa = true
  next()
}
```

so, I tried to render no ssr mode with server middleware, then It works. but often there's need ssr.

how can I use recaptcha module with pages that need ssr?

thanks.

**Comment by mvrlin** [comment]
Hello! I don't think it's really possible because ReCaptcha is server-side only, but you can render an empty `div` with recaptcha class

**Comment by bongjinpark1** [comment]
I'm very sorry. This problem is turned out occurred from other component. not recaptcha component. Thanks.
