### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Dahdoul** [nuxt-community/recaptcha-module#14]
After installing and configuring the module, I got the below error on 

`yarn run dev or yarn run build`

Nuxt v2.6.3

 FATAL  The 'request' argument must be string. Received type undefined                                                                                                              20:57:54
  at node_modules/esm/esm.js:1:220358
  at Module.<anonymous> (node_modules/esm/esm.js:1:289859)
  at Resolver.n [as esm] (node_modules/esm/esm.js:1:273820)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:624:31)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:164:36)
  at promise.then (node_modules/@nuxt/utils/dist/utils.js:1790:43)

**Comment by mvrlin** [comment]
Hello! What is nuxt version are you using?

**Comment by mvrlin** [comment]
https://codesandbox.io/s/r1o71w59lq
Everything works

**Comment by Dahdoul** [comment]
it turns out that Nuxt recaptcha-module causing the error error.

**Comment by Ramarti** [comment]
How did you fix this? @Dahdoul 
I'm encountering same issue with other modules

**Comment by Dahdoul** [comment]
@Ramarti try to delete node_modules and .nuxt and run yarn/npm  again.

for me I had to remove nuxt recaptcha entirely to be able to continue working on the project, I will install it later on and see if the problem was fixed.

**Comment by Ramarti** [comment]
The project works when I comment out that entry in the modules array of nuxt.config.js
Problem is, I do need this ( https://github.com/nuxt-community/nuxt-i18n ) to work now.

Seeing the same error in another module makes me think nuxt changed something in the way it adds modules and some modules have not updated yet, maybe?

Anyway, I hoped recaptcha-module fixed it so I can port it to nuxt-i18n or something.

I can't find that 'request' argument in requireModule in nuxt core, pretty lost

**Comment by Dahdoul** [comment]
@Ramarti I tried to look for request too but with no hope, as you said it might be something changed in  nuxt core and modules need to update accordingly
