### ISSUE TITLE
Nuxt Build Error

### ISSUE THREAD

**Issue by kevinalexandersurjadi** [nuxt-community/recaptcha-module#17]
I got an error

```
Property '$recaptcha' does not exist on type 'Page'.
```

I have done adding dependencies and add it to modules at nuxt.config.ts
package.json
```
...
"dependencies": {
    ...
    "@nuxtjs/recaptcha": "^0.4.1",
    ...
},
...
```
nuxt.config.ts
```
   ...
   modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    '@nuxtjs/recaptcha',
  ],
  recaptcha: {
    hideBadge: process.env.NODE_ENV !== 'development',
    siteKey: <MY_SITE_KEY>,
    version: 3
  },
  ...
```

and what I have been doing in the Page is something like this
```
async mounted() {
    await this.$recaptcha.init();
}

async submitForm() {
    try {
      const token = await this.$recaptcha.execute('login');
    } catch (error) {
      console.error(error)
    }
}
```

And I got error in those lines with $recaptcha when I ran nuxt build. I am using @nuxt/cli v2.6.1
. Plus, in development mode, it runs perfectly. Can you please help?

**Comment by mvrlin** [comment]
I just built `example/v3` and I get no errors. Do you get any errors while building?

**Comment by kevinalexandersurjadi** [comment]
Yeah, i got no errors while building the example.

Anyway, that problem was my bad. I couldn't access this.$recaptcha on that submitForm method, maybe because I couldn't get the context. So I solved it by using store action, there I could get the context and could access this.$recaptcha perfectly. Finally, my project could be built without errors. Perhaps, It will be better that way.
