### ISSUE TITLE
Changing v2 language

### ISSUE THREAD

**Issue by marius815** [nuxt-community/recaptcha-module#18]
Would it be possible to add language support for recaptcha? If the requested script has a `hl` querystring parameter with one of the [supported language codes](https://developers.google.com/recaptcha/docs/language), we would get localized strings. E.g. `https://www.google.com/recaptcha/api.js?hl=fr`

See [this answer on SO](https://stackoverflow.com/a/28807581/1828306)

**Comment by mvrlin** [comment]
Hello! Sure, I will add language support soon 😄

**Comment by mvrlin** [comment]
@marius815 Language support added in the latest release. Update your dependencies 😉

**Comment by marius815** [comment]
Excellent! Works perfectly :smile:
