### ISSUE TITLE
await this.$recaptcha.execute method returning null

### ISSUE THREAD

**Issue by Pilfer** [nuxt-community/recaptcha-module#2]
Hey there, I'm not sure if this module is even production ready or not but I was playing with it and can't seem to get the captcha response to return anything. I see that it's calling the underlying window.grecaptcha.execute method, but it's not doing anything else past that.

I'm in a mostly freshly generated nuxt.js project (generated via official npx) and pretty much copy/pasted the example code in. 

Since this module is marked "WIP", does that mean this functionality just isn't here yet?

Thanks!

**Comment by pi0** [comment]
@Pilfer Example should be fully working. Ensure you have setup correct reCaptcha key and allowed it for localhost domain.

**Comment by Pilfer** [comment]
@pi0 I confirmed that my recaptcha setup is correct. I'm having some misc workbox issues as well within the same project, so I think that something inside my nuxt config is broken. Probably my fault - closing this issue.

Thanks!

**Comment by klliks-com** [comment]
> @pi0 I confirmed that my recaptcha setup is correct. I'm having some misc workbox issues as well within the same project, so I think that something inside my nuxt config is broken. Probably my fault - closing this issue.
> 
> Thanks!

Hi Man!
been trying to contact you in any possible way.
I really need your help - willing to pay.

**Comment by efesezer** [comment]
What was your fault? I am still facing this issue and I couldnt mange the solve it. How did you solve your own problem?

**Comment by Pilfer** [comment]
> What was your fault? I am still facing this issue and I couldnt mange the solve it. How did you solve your own problem?

This was three years ago so I don't even remember which codebase I used this module for lol, but I'd check your reCAPTCHA settings (key and version) and if you're using SSL or not.
