### ISSUE TITLE
dataSize doesn't work???!

### ISSUE THREAD

**Issue by ouahibAbdou** [nuxt-community/recaptcha-module#20]
this is a screenshot:
![image](https://user-images.githubusercontent.com/30089652/59958028-36646600-9498-11e9-9d0f-b5c4b934544c.png)

**Comment by mvrlin** [comment]
Hello, there's no option for that.

**Comment by ricardogobbosouza** [comment]
@ouahibAbdou no option `dataSize`, its a property of componente 
https://github.com/nuxt-community/recaptcha-module/blob/master/lib/recaptcha.vue#L4

**Comment by ricardogobbosouza** [comment]
@mvrlin can closed?

**Comment by mvrlin** [comment]
@ricardogobbosouza data-size should be passed as prop for a component:

```html
<recaptcha data-size="compact" />
```
