### ISSUE TITLE
captcha not adjusting for media screens 

### ISSUE THREAD

**Issue by oeyvindkped** [nuxt-community/recaptcha-module#26]
The image selector is not consistent in its placement on mobile screens. Sometimes it adjust itself and its perfectly centered, sometimes the image selector pops out to the right so that half of the images are unreachable. 

It seems that issue is in the inline styling of the captcha element, it wont register and adjust for the screen width. Even though this happens on all smaller screen-sizes, it seems to especially apply for screen widths of 414px.
<img width="427" alt="Skjermbilde 2019-10-16 kl  16 42 21" src="https://user-images.githubusercontent.com/52649338/66929825-fc653400-f033-11e9-8864-b9e126aeb4d9.png">

**Comment by mvrlin** [comment]
Hello, that's the Google captcha issue itself.  I have nothing to do with it.
