### ISSUE TITLE
How to reset the recaptcha after form reset?

### ISSUE THREAD

**Issue by sushiljic** [nuxt-community/recaptcha-module#27]
I am using recaptcha v2.
Once the form is being submitted after successful recaptcha, i need to reset the recaptcha 
Since i am on the same page.
So how can i obtain it?
I have tried with 
`this.$recaptcha.init()` 
but doesnot work
![Screen Shot 2019-10-20 at 13 58 53](https://user-images.githubusercontent.com/5524563/67156731-47d45680-f342-11e9-80d8-ec3668caacdb.png)

**Comment by mvrlin** [comment]
Hello! Added a function in the new release! 😁
Now you can use:

```javascript
this.$recaptcha.reset()
```
