### ISSUE TITLE
ReCaptcha error: Failed to load script

### ISSUE THREAD

**Issue by aaaguirrep** [nuxt-community/recaptcha-module#3]
Hi, I am trying the plugin but when the page loads the mounted function it shows the next issue:

"ReCaptcha error: Failed to load script at HTMLScriptElement.<anonymous>"

Do you know the issue?

Thanks in advance.

Regards,
Arsenio

**Comment by mvrlin** [comment]
@aaaguirrep Hey! Can you show your nuxt.config?

**Comment by aaaguirrep** [comment]
Sure @mvrlin 

`const pkg = require('./package')

module.exports = {
  mode: 'spa',

  /*
  ** Headers of the page
  */
  head: {
    title: pkg.name,
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: pkg.description }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
      {
        rel: 'stylesheet',
        href: 'https://use.fontawesome.com/releases/v5.7.1/css/all.css',
        integrity:
          'sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr',
        crossorigin: 'anonymous'
      },
      {
        href:
          'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800',
        rel: 'stylesheet',
        type: 'text/css'
      }
    ]
  },

  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#fff' },

  /*
  ** Global CSS
  */
  css: [{ src: '~/assets/scss/style.scss', lang: 'scss' }],

  /*
  ** Plugins to load before mounting the App
  */
  plugins: [],

  /*
  ** Nuxt.js modules
  */
  modules: [
    // Doc: https://bootstrap-vue.js.org/docs/
    'bootstrap-vue/nuxt',
    '@nuxtjs/recaptcha'
  ],

  recaptcha: {
    hideBadge: true, // Hide badge element
    siteKey: '6Ldbf5AUAAAAAMf92DUs9bTojXLrWuEkahVDIpEo' // Site key for requests
  },
  /*
  ** Build configuration
  */
  build: {
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
      // Run ESLint on save
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    },
    terser: {
      terserOptions: {
        compress: {
          drop_console: true
        }
      }
    }
  }
}
`

**Comment by mvrlin** [comment]
@aaaguirrep all looks good. Try to open in your browser https://www.google.com/recaptcha/api.js
Is it throwing an Error?

**Comment by d4rkr3pt0r** [comment]
Same problem here.
`
The resource from “https://www.google.com/recaptcha/api.js?render=xxxxxxxxxxxxxxx” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
Error: ReCaptcha error: Failed to load script
`
No error with https://www.google.com/recaptcha/api.js But the mentioned URL (in error) is giving me a `bad request - 400 error`

**Comment by aaaguirrep** [comment]
@mvrlin it looks good. See the response.

```
/* PLEASE DO NOT COPY AND PASTE THIS CODE. */(function(){var CFG='___grecaptcha_cfg';if(!window[CFG]){window[CFG]={};}var GR='grecaptcha';if(!window[GR]){window[GR]={};}window[GR].ready=window[GR].ready||function(f){(window[CFG]['fns']=window[CFG]['fns']||[]).push(f);};(window[CFG]['render']=window[CFG]['render']||[]).push('onload');window['__google_recaptcha_client']=true;var po=document.createElement('script');po.type='text/javascript';po.async=true;po.src='https://www.gstatic.com/recaptcha/api2/v1549866690836/recaptcha__es_419.js';var elem=document.querySelector('script[nonce]');var n=elem&&(elem['nonce']||elem.getAttribute('nonce'));if(n){po.setAttribute('nonce',n);}var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(po, s);})();
```

**Comment by mvrlin** [comment]
@aaaguirrep could you provide your browser, system?

**Comment by d4rkr3pt0r** [comment]
@aaaguirrep mine is:
Windows 10 Version 10.0.17134.590
Tested browsers : `Firefox Nightly 67.0a1` , `Chrome Version 72.0.3626.109 (Official Build) (64-bit)`
This is Chrome error:
'
api.js:1 Failed to load resource: the server responded with a status of 400 ()
app.js:2108 Uncaught Error: ReCaptcha error: Failed to load script
    at HTMLScriptElement.<anonymous> (app.js:2108)
'

**Comment by aaaguirrep** [comment]
@mvrlin sure:
Chrome --> Versión 72.0.3626.109 (Build oficial) (64 bits)
Firefox Quantum --> 65.0.1 (64-bits)

**Comment by mvrlin** [comment]
@aaaguirrep, @d4rkr3pt0r are you using v3 sitekey?

**Comment by aaaguirrep** [comment]
No, I am using v2.

**Comment by mvrlin** [comment]
> No, I am using v2.

For now it's support v3 only. I will try to add v2 support during this week.

**Comment by aaaguirrep** [comment]
Ok, I go to check, I read the information and it doesnt specify the support for v3.

**Comment by d4rkr3pt0r** [comment]
@mvrlin It's working fine using V3 sitekey. But I rather wait for V2 compatibility. Thanks

**Comment by mvrlin** [comment]
@aaaguirrep, @d4rkr3pt0r try the new version

**Comment by aaaguirrep** [comment]
Hi @mvrlin, is there an issue in the documentation about a comma at the end of the options? If you see the version attribute there is a comma after Number.

````
{
  // ...
  recaptcha: {
    hideBadge: Boolean, // Hide badge element (v3)
    siteKey: String,    // Site key for requests
    version: Number,    // Version
  },
  // ...
}
````

**Comment by mvrlin** [comment]
@aaaguirrep Hey, no, it's just the way I like to write code 😄. You can write with or without the comma.

**Comment by mattander91** [comment]
I couldn't get the recaptcha checkbox (V2) to render on one of my pages until I added the script tag in nuxt.config.js.

`head: {
    script: [
      { src: 'https://www.google.com/recaptcha/api.js', async: true, defer: true}     
    ]
}`
Hopefully this is helpful to anyone else experiencing the same issue.

**Comment by leonhoffmann86** [comment]
Did you fill in the siteKey in the reCAPTCHA options as a String? This fixed the same error for me.

**Comment by echeverriadev** [comment]
This is showing in my app, is this issue solved? @[aaaguirrep](https://github.com/aaaguirrep)

**Comment by Wilders** [comment]
> 

We have the same issue in our app, from time to time.
