### ISSUE TITLE
No guide on how to use recaptcha-module

### ISSUE THREAD

**Issue by jalasem** [nuxt-community/recaptcha-module#32]
the README only specifies how to install and configure recaptcha-module in our nuxt project. How do I use it in my project to validate that client signing is human and not a bot?

**Comment by pelkinn** [comment]
> the README only specifies how to install and configure recaptcha-module in our nuxt project. How do I use it in my project to validate that client signing is human and not a bot?

look at the examples folder

**Comment by jalasem** [comment]
Yeah...I later saw it. Do you mind if I make a pull request for the README?
It will be much better if one can get all the necessary information in the README since it's not much or a robust package

**Comment by mvrlin** [comment]
> Yeah...I later saw it. Do you mind if I make a pull request for the README?
> It will be much better if one can get all the necessary information in the README since it's not much or a robust package

Sure 😊

**Comment by seyfer** [comment]
this helped me
https://developers.google.com/recaptcha/docs/verify
https://stackoverflow.com/questions/51507695/google-recaptcha-v3-example-demo
