### ISSUE TITLE
How to actually use the captcha on a page?

### ISSUE THREAD

**Issue by cipiasentini** [nuxt-community/recaptcha-module#42]
Documentation is great for setting up, but how do I actually use the recaptcha on a given page? After seting it up, I'm intercepting the request params but there's no captcha params at all.

**Comment by cipiasentini** [comment]
I think I've figured it out, I've just included the recaptcha component inside the component I wanted to use. Now I'm getting a key validation error on page load. Even though I've made sure to have the correct public key setted up (and the private one on the server). [error image](https://imgur.com/pJMV7wS) [config image](https://imgur.com/oiCuf9o)

**Comment by elise-boinnot** [comment]
Examples for v2 and v3 are here https://github.com/nuxt-community/recaptcha-module/tree/master/example

**Comment by ramesh-maharjan** [comment]
const token = await this.$recaptcha.execute('login') what's the login that we are passing? if you look at the example v3 its not referring to anything

**Comment by irvv17** [comment]
> I think I've figured it out, I've just included the recaptcha component inside the component I wanted to use. Now I'm getting a key validation error on page load. Even though I've made sure to have the correct public key setted up (and the private one on the server). [error image](https://imgur.com/pJMV7wS) [config image](https://imgur.com/oiCuf9o)

did you solve this?

**Comment by eliseboinnot** [comment]
> const token = await this.$recaptcha.execute('login') what's the login that we are passing?

“login” is just a name for the action the recaptcha is associated with. It can be anything. It will appear on the dashboard, more info [here](https://developers.google.com/recaptcha/docs/v3#actions)
