### ISSUE TITLE
Google recaptcha global support (suggestion)

### ISSUE THREAD

**Issue by christian-bravo7** [nuxt-community/recaptcha-module#46]
This is a suggestion to change the recaptcha script to global mode

https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally

This would support countries where ReCAPTCHA content is not accessible (i.e China)

`const API_URL = 'https://www.recaptcha.net/recaptcha/api.js'`

**Comment by lat1992** [comment]
Some of my project is collaborate with chinese devs, so I need to change this url too.
