### ISSUE TITLE
Lack of documention

### ISSUE THREAD

**Issue by Sunhat** [nuxt-community/recaptcha-module#47]
No information on how to use this with v2 invisible.

Useless devs making packages everywhere...

**Comment by ThePooN** [comment]
https://github.com/nuxt-community/recaptcha-module/tree/master/example/v3

> Useless devs making packages everywhere...

You don't deserve us or any of the open-source community for that matter. Examples, docs, or not. I feel guilty for actually helping you.

**Comment by JoaquimLey** [comment]
A free piece of software where there are ACTUAL examples but you figure you should complain about other's FREE work. 

Great job showing your character. I agree with @ThePooN.

**Comment by tircomnicu** [comment]
Thank you @ThePooN.

**Comment by Sunhat** [comment]
phahaha

**Comment by ThePooN** [comment]
This is your original message, which I directly answered.
![image](https://user-images.githubusercontent.com/4985725/84595851-87fcc200-ae5a-11ea-8b32-d7f98745417a.png)

Either way, sure, there is the invisible v2 example you're looking for. https://github.com/nuxt-community/recaptcha-module/tree/master/example/v2

Lastly, I do not see how what I said, the "arrogance" you've brought up (which you've demonstrated having more than I have), or my nickname (and its invented meanings, for that matter) warrant another personal attack, after having already attacked this project's author.

Lastly, I do not think making another personal attack at this project's author/collaborators was the right move. You've shown infinitely more arrogance than I did.  
If you have an issue with my nickname or its meaning you're assuming from a meme site (spoiler: it actually has nothing to do with NSFW content), you should at least bring it up privately. Not on a public project's issues.

There is no point in leaving this open any longer. Can you please lock this @mvrlin?
