### ISSUE TITLE
Error: Could not compile template

### ISSUE THREAD

**Issue by VarghaSabee** [nuxt-community/recaptcha-module#5]
Hello. I`m using  "nuxt": "^1.4.0", and after install the package I have this error in my project
ERROR
  Error: Could not compile template .
...\node_modules\@nuxtjs\recaptcha\lib\plugin.js: error is not defined
 - builder.js:471 Promise.all.templatesFiles.map
   [....]/[nuxt]/lib/builder/builder.js:471:17

**Comment by mvrlin** [comment]
@VarghaSabee Hello! This module is for Nuxt 2.4^

**Comment by manniL** [comment]
@mvrlin better mention that in the readme.

**Comment by VarghaSabee** [comment]
Thanks for the answer

**Comment by mvrlin** [comment]
@VarghaSabee sry, it's supports, it's just had a bug. In a few minutes I will release the new version 😊

**Comment by VarghaSabee** [comment]
I will wait 😊 Thx

**Comment by mvrlin** [comment]
@VarghaSabee just released. Try it out!

**Comment by VarghaSabee** [comment]
One more time thx for the fast support it`s works 😊 **Solved**
