### ISSUE TITLE
reset() multiple component

### ISSUE THREAD

**Issue by jemjov41** [nuxt-community/recaptcha-module#54]
i'm using 2 recaptcha component inside login form and otp modal, 
but i can't reset recaptcha inside my modal, but its keep reseting recaptcha component in login form.

if i'm just use 1 recaptcha component inside modal and remove recaptcha in login form, reset() is work to reset my recaptcha inside modal.

is that possible to using more than 1 recaptcha component in one page? and reset multiple of it or specifically?

**Comment by owalid** [comment]
I think is not possible because `reset()` use the window object for reset the recaptcha.
You can try to reset with `ref` in your components.
see here: https://github.com/nuxt-community/recaptcha-module/blob/master/lib/plugin.js#L155
