### ISSUE TITLE
Serializing native function: Boolean

### ISSUE THREAD

**Issue by Tjark-Kuehl** [nuxt-community/recaptcha-module#55]
Having an issue running this with typescript in **spa mode** that I cannot even start it with default options.

Maybe having an error compiling this

```JS
 inject('recaptcha', new ReCaptcha(<%= serialize(options) %>))
```

**Comment by Tjark-Kuehl** [comment]
Nvmd was a config mistake

**Comment by sg1asgard** [comment]
@Tjark-Kuehl  I have the exact same error but the config looks OK.
What was the exact issue and solution in your case?

**Comment by Tjark-Kuehl** [comment]
> @Tjark-Kuehl I have the exact same error but the config looks OK. What was the exact issue and solution in your case?

I'm rly not sure anymore tbh. I can look around my repositories but I dont think that I can find how I solved it.
Where is this even used maybe I can look at that I just knew that I've used ReCaptcha v3 in the end.
