### ISSUE TITLE
Remove captcha properly while navigating

### ISSUE THREAD

**Issue by plduhoux** [nuxt-community/recaptcha-module#6]
After validating a form and passing the captcha, the iframe from google (bottom right corner) does not disappear.

Navigating on pages which does not contain the captcha should not display this iframe.

I tried to remove it manually in the `beforeDestroy`from my nuxt page component : 
```
  beforeDestroy() {
    //remove initiated recaptcha
    let recap = document.querySelector(".grecaptcha-badge")
    recap.parentNode.removeChild(recap)
  }
```

But then it does not reload when I navigate to a page supposed to contain the captcha

I think this behavior should be handled.

**Comment by mvrlin** [comment]
Hello! You want to destroy recaptcha?

**Comment by plduhoux** [comment]
I just mounted the project so it should be the latest one : mine is 0.2.2

Indeed, I want to load recaptcha only on the sign up page. I don't want to have the small iframe (bottom right hand corner) from google recaptcha on other pages.

**Comment by mvrlin** [comment]
@plduhoux did you try to pass `hideBadge: true` option in the `nuxt.config.js` file?

**Comment by plduhoux** [comment]
yes, my module config is : 
```
[
      "@nuxtjs/recaptcha",
      {
        hideBadge: true, // Hide badge element (v3)
        siteKey: "xxxxxxxxxxxxx", // Site key for requests
        version: "3" // Version
      }
    ]
```
Do you have this little iframe in the bottom right hand corner or could it be related t google policies for GDPR ?
![Capture d’écran 2019-03-18 à 09 03 00](https://user-images.githubusercontent.com/687923/54515589-ca380a80-495c-11e9-974e-50a8cbb80802.png)

**Comment by mvrlin** [comment]
Very strange. It should hide the badge. Do you have any errors in the console?

**Comment by ironwebstar** [comment]
@mvrlin 
I am facing same issue.
The bottom right captcha badge is showing on every page.
```
[
      '@nuxtjs/recaptcha', {
        hideBadge: true,
        siteKey: env.RECAPTCHA_SITE_KEY,
        version: 3
      }
]
```
This is my config for reCaptcha v3 in nuxt.config.js.

I think the reCaptcha badge should be hidden if `hideBadeg` is `true`. What do you think?

**Comment by benlutz** [comment]
i know it's an old thread, but I just fixed it with `size: 'invisible'` in combination with `hideBadge: true`. That did the trick for me.

@ironwebstar

**Comment by ironwebstar** [comment]
@benlutz Thank you! I will test when I have got a time for it.

**Comment by sa8ab** [comment]
@ironwebstar an unrelated question, how do you send the site-key to `env` ?

**Comment by arielkuzminski** [comment]
@benlutz 
This solution didn't work :( 
More over solution provided by @plduhoux broke the app after coming back to allready instantiated recaptcha.

So my ugly solution but fully working looks like this:

`    async mounted() {
        await this.$recaptcha.init();
        // show allready initiated recaptcha
        const recaptchaBadgeElement = document.querySelector('.grecaptcha-badge');
        if (recaptchaBadgeElement) {
            recaptchaBadgeElement.style.visibility = 'visible';
        }
    },
    destroyed() {
        //  remove initiated recaptcha
        const recaptchaBadgeElement = document.querySelector('.grecaptcha-badge');
        if (recaptchaBadgeElement) {
            recaptchaBadgeElement.style.visibility = 'hidden';
        }
    },`

**Comment by ennoucas** [comment]
Same here couldn't find a better solution than the one provided by @arielkuzminski
