### ISSUE TITLE
Can v2 and v3 be used at the same time ?

### ISSUE THREAD

**Issue by belgacea** [nuxt-community/recaptcha-module#61]
[An example use case would be to verify an user getting a low score from V3 using V2.](https://github.com/google/recaptcha/issues/279)

**Comment by Marcosaurios** [comment]
Take a look at this PR https://github.com/nuxt-community/recaptcha-module/pull/70, you could change the plugin settings in runtime and switch from V2 to V3 and viceversa whenever you need it, instead of having 2 instances of the plugin as you suggest
