### ISSUE TITLE
$recaptcha.getResponse() rejected with `undefined` when used wrong key

### ISSUE THREAD

**Issue by zoxon** [nuxt-community/recaptcha-module#63]
```js
async onSubmit() {
  try {
    const token = await this.$recaptcha.getResponse();
    this.recaptcha = token;

    console.log(this.$data);
  } catch (error) {
    console.log(error); // undefined
  }
}
```

Configuration
```js
{
  siteKey: "6LeXSaMZAAAAAKSyzQHnpkZKIN7bbnXq3nm1O6Go",
  size: "invisible",
  hideBadge: true,
  version: 2
}
```

Reproduction url
https://codesandbox.io/s/falling-water-p3zl4?file=/pages/index.vue:998-1039

**Comment by ems1985** [comment]
There seems to be a general problem with error handling. These are some errors I got when I used a key that did not have proper domains configured:

![image](https://user-images.githubusercontent.com/34405275/100655071-0edf2180-334b-11eb-8b84-a687206abdc1.png)

![image](https://user-images.githubusercontent.com/34405275/100655084-130b3f00-334b-11eb-86aa-436809c2285a.png)
