### ISSUE TITLE
Closing the documentation gap

### ISSUE THREAD

**Issue by JonathanAlumbaugh** [nuxt-community/recaptcha-module#67]
Hey y'all, have implemented this a couple of times, but not often enough that I remember everything off the top of my head. Thought I'd try to contribute a couple code snippets that I use for reference to help others who are looking to use this module. Wasn't sure if this would warrant a pull request or not. If I'm dropping this in the wrong spot my apologies.

After installing the module and adding a config in `nuxt.config.js` following the [existing docs](https://github.com/nuxt-community/recaptcha-module), I set up a serverMiddleware to handle sending the recaptcha token along to the recaptcha service with the secret sitekey, without exposing it to the client (though I've ended up exposing my sitekey in commits more than once, ha).

In `nuxt.config.js`:
```
  serverMiddleware: ['~/api/recaptchaAuth'],

  ...

    modules: [ '@nuxtjs/recaptcha'],

  ...

  recaptcha: {
    hideBadge: true, // Hide badge element (v3 & v2 via size=invisible)
    siteKey: 'YOUR_SITEKEY', // Site key for requests
    version: 3, // Version, I like 3 because it's invisible 👾 
  },
```

In `~/api/recaptchaAuth`:
```
const app = require('express')()
const cors = require('cors')
const bodyParser = require('body-parser')
import axios from 'axios' // I want to use @nuxtjs/axios here but not savvy enough to figure out how to import 🤷‍♂️ 

const SECRET_KEY = 'YOUR_SECRET_KEY_HERE'

app.use([bodyParser.json(), cors()])
// I allowed cors here so I could test from 127.0.0.1 
// in addition to localhost, but you may want to remove 
// this before publishing your app/site.
app.options('*', cors()) 

app.post('/recaptcha', async (req, res) => {
  try {
    const { host } = req.headers
    const { token } = req.body

    if (!token) {
      res.status(400).send('No token!')
      throw 'No token!'
    }

    const { data } = await axios.post(
      `https://www.google.com/recaptcha/api/siteverify?secret=${SECRET_KEY}&response=${token}`,
    )

    res.send(data)
  } catch (e) {
    console.log('ReCaptcha error:', e)
    res.status(500).send(`<p>ReCaptcha error:</p> <pre>${e}</pre>`)
  }
})

module.exports = app
```

In the component/page where you want to use recaptcha, add a method (in this example, `~/components/nav.vue`, to hide and show contact info):
```
  methods: {
    async show() {
      try {
        const token = await this.$recaptcha.execute('contact') //my action is named contact but this can be whatever
        const res = await this.$axios.$post('/recaptcha', { token })

        if (res.success === true) this.$modal.show('contact-modal')
        else throw new Error('looks like you might not be a human :(')
      } catch (e) {
        console.log('Error:', e)
      }
    },
  },
```

And to complete my V3 example, I need to include the disclaimer:
```
  <p class="disclaimer">
    This site is protected by reCAPTCHA and the Google
    <a href="https://policies.google.com/privacy">Privacy Policy</a>
    and
    <a href="https://policies.google.com/terms">Terms of Service</a>
    apply.
  </p>
```

**Comment by lansolo99** [comment]
@JonathanAlumbaugh Agree with you, the doc is a bit lacking, especially when people are not accustomed to handle the server side implementation within ssr Nuxt. I refactored my error handling using your snippet. 
Thx!
