### ISSUE TITLE
ReCaptcha error: Failed to execute 

### ISSUE THREAD

**Issue by BenJChen** [nuxt-community/recaptcha-module#8]
when I use reCaptcha in asyncData,it was given an error：Failed to execute ；
can I  use reCaptcha in asyncData？Because some interface runs in asyncData。

**Comment by mvrlin** [comment]
Hi! `asyncData` is running server-side on the first request and then client-side when navigating routes. I think it's possible if you check using `process.client` or `process.server`.

**Comment by BenJChen** [comment]
> 嗨！`asyncData`在第一个请求上运行服务器端，然后在导航路由时运行客户端。我认为你可以检查使用`process.client`或`process.server`。

Whether reCaptcha can only be run on the client？

**Comment by mvrlin** [comment]
Yes.

**Comment by ricardogobbosouza** [comment]
@mvrlin can closed?
