### ISSUE TITLE
error message: "Error message to website owners: Invalid key type"

### ISSUE THREAD

**Issue by mangrove108** [nuxt-community/recaptcha-module#84]
just updated the package from 1.0.2 to 1.0.3, the above error appeared, this is the setting:

(nuxt.config.js)
modules: [
'@nuxtjs/axios',
'@nuxtjs/device',
'@nuxtjs/recaptcha'....
],
recaptcha: {
hideBadge: false,
siteKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
version: 3,
size: 'invisible'
},

component usage is like:
`<recaptcha />`

will wait for the fix. 👍

**Comment by andrewmurraydavid** [comment]
@mangrove108 I've just created a PR to attempt to fix this #85 

Could you take a look and try testing it out?

Thanks!
