### ISSUE TITLE
v2 callback?

### ISSUE THREAD

**Issue by cannap** [nuxt-community/recaptcha-module#9]
hi is there a way to have a callback when the captcha is solved?

**Comment by mvrlin** [comment]
Hi! Sure. Here's two ways:

```js
async onSubmit () {
  try {
    const token = this.$recaptcha.getResponse()
    console.log(token)
  } catch (error) {
    // Handle error
  }
}
```

or

```js
onSubmit () {
  this.$recaptcha.getResponse()
    .then(token => console.log(token))
    .catch(error => {
      // Handle error
    })
}
```

**Comment by cannap** [comment]
thanks 
but i need to press the button for that as example: the captcha is no longer valid on the server now i have the button disabled but when he tries to solve the captcha again i need to reset that error

**Comment by mvrlin** [comment]
You mean, that you want events like:
`@error="onError"` and `@success="onSuccess"`?

**Comment by cannap** [comment]
yes something like that :D

**Comment by mvrlin** [comment]
@cannap check the new update :). Should be working now.

**Comment by cannap** [comment]
holy s*** thank you will check this out tomorrow

**Comment by nicoagp** [comment]
> You mean, that you want events like: `@error="onError"` and `@success="onSuccess"`?

Thank you. 
This is helpful and currently working. 
Shouldn't be added to the documentation ?
