### ISSUE TITLE
add support for @nuxtjs/composition-api

### ISSUE THREAD

**Issue by maemaemae3** [nuxt-community/recaptcha-module#92]
Hi, I want to use this module with [@nuxtjs/composition-api](https://github.com/nuxt-community/composition-api), so I tried to use it from `useContext();`, but it doesn't work.

```javascript
import { defineComponent, onMounted, useContext } from '@nuxtjs/composition-api';

export default defineComponent({
  setup() {

    const { $recaptcha } = useContext();

    onMounted(async () => {
      await $recaptcha.init();
    });

    ...

  }
})
```

Then, I found that there is no type definition for `useContext()`, so I added this part to `index.d.ts`, but it seems not working,

```javascript
declare module '@nuxt/types' {
  interface Context {
    $recaptcha: ReCaptchaInstance
  }
}
```

However, when I added this to my components directly, it works perfectly.

```javascript
import { ReCaptchaInstance } from '@nuxtjs/recaptcha';

declare module '@nuxt/types' {
  interface Context {
    $recaptcha: ReCaptchaInstance
  }
}
```

Am I doing something wrong?
If there is some other way to make it work with adding type definition to `index.d.ts`, I'll do it and make a PR.

**Comment by mvrlin** [comment]
@maemaemae3 Hey! You can use it throught the `root`

```typescript
export default defineComponent({
  setup(_, { root }) {
    const recaptcha = root.$recaptcha
    
    onMounted(async () => {
      await recaptcha.init()
    })
  },
})
```

**Comment by Red-Asuka** [comment]
The same problem bothered me

**Comment by weicheng2138** [comment]
> Hi, I want to use this module with [@nuxtjs/composition-api](https://github.com/nuxt-community/composition-api), so I tried to use it from `useContext();`, but it doesn't work.
> 
> ```js
> import { defineComponent, onMounted, useContext } from '@nuxtjs/composition-api';
> 
> export default defineComponent({
>   setup() {
> 
>     const { $recaptcha } = useContext();
> 
>     onMounted(async () => {
>       await $recaptcha.init();
>     });
> 
>     ...
> 
>   }
> })
> ```
> 
> Then, I found that there is no type definition for `useContext()`, so I added this part to `index.d.ts`, but it seems not working,
> 
> ```js
> declare module '@nuxt/types' {
>   interface Context {
>     $recaptcha: ReCaptchaInstance
>   }
> }
> ```
> 
> However, when I added this to my components directly, it works perfectly.
> 
> ```js
> import { ReCaptchaInstance } from '@nuxtjs/recaptcha';
> 
> declare module '@nuxt/types' {
>   interface Context {
>     $recaptcha: ReCaptchaInstance
>   }
> }
> ```
> 
> Am I doing something wrong? If there is some other way to make it work with adding type definition to `index.d.ts`, I'll do it and make a PR.

I was thinking that i should config "@nuxtjs/recaptcha" in tsconfig.json. But it doesn't work at all.
`"compilerOptions": {
        "types": [
            "@nuxtjs/recaptcha",
        ]
    },`

**Then I did your way to add the type definition in index.d.ts and every works fine**. Of course remember to set the **siteKey** in nuxt.config.js

**Comment by emretepedev** [comment]
> The same problem bothered me

@weicheng2138 below codes work like a charm for me. good luck!

in package.json
```js
"dependencies": {
    "@nuxtjs/recaptcha": "^1.0.4",
},
```

in nuxt.config.js,
```js
export default {
    modules: [
        '@nuxtjs/recaptcha',
    ],

    recaptcha: {
        /* your  config here */
    },
}
```

in *.vue
```js
import { defineComponent, useContext } from '@nuxtjs/composition-api'

export default defineComponent({

```

**Comment by emretepedev** [comment]
> The same problem bothered me

@weicheng2138 below codes work like a charm for me. good luck!

in package.json
```js
"dependencies": {
    "@nuxtjs/recaptcha": "^1.0.4",
},
```

in nuxt.config.js,
```js
export default {
    modules: [
        '@nuxtjs/recaptcha',
    ],

    recaptcha: {
        /* your  config here */
    },
}
```

in *.vue
```js
import { defineComponent, useContext, onMounted } from '@nuxtjs/composition-api'

export default defineComponent({
  setup() {
    // context
    const { $recaptcha } = useContext()
    
    // hooks
    onMounted(async () => {
      await $recaptcha.init() // replace with `init`, whatever you want
    })
  }
})
```

**Comment by weicheng2138** [comment]
> in *.vue
> 
> ```js
> import { defineComponent, onMounted } from '@nuxtjs/composition-api'
> 
> export default defineComponent({
>   setup(_, context) {
>     // root variables
>     const $recaptcha= context.root.$recaptcha
>     
>     // hooks
>     onMounted(async () => {
>       await $recaptcha.init() // replace with `init`, whatever you want
>     })
>   }
> })
> ```

@emretepedev Thanks for your solution. It does the work very well. However, it show up with deprecated message below.

<img width="807" alt="2022-02-01 10 45 55" src="https://user-images.githubusercontent.com/13548635/151906802-548d28da-b270-4b2a-b03d-f047ec5160a6.png">

 If you are going to to migrate your project to Nuxt 3, you may need to think about it.

**Comment by emretepedev** [comment]
> > in *.vue
> > ```js
> > import { defineComponent, onMounted } from '@nuxtjs/composition-api'
> > 
> > export default defineComponent({
> >   setup(_, context) {
> >     // root variables
> >     const $recaptcha= context.root.$recaptcha
> >     
> >     // hooks
> >     onMounted(async () => {
> >       await $recaptcha.init() // replace with `init`, whatever you want
> >     })
> >   }
> > })
> > ```
> 
> @emretepedev Thanks for your solution. It does the work very well. However, it show up with deprecated message below.
> 
> <img alt="2022-02-01 10 45 55" width="807" src="https://user-images.githubusercontent.com/13548635/151906802-548d28da-b270-4b2a-b03d-f047ec5160a6.png">
> 
> If you are going to to migrate your project to Nuxt 3, you may need to think about it.

i'll investigate this situation however i did not use with root. i use `useContext()`. Did you try that? Do you have any error?

**Comment by weicheng2138** [comment]
> i'll investigate this situation however i did not use with root. i use `useContext()`. Did you try that? Do you have any error?

@emretepedev  I do use `useContext()` and it works fine. But there is no **full typing and autocompletion support**.

After adding the code below in `index.d.ts`, typing and autocompletion support are back.
> ```js
> import { ReCaptchaInstance } from '@nuxtjs/recaptcha';
> 
> declare module '@nuxt/types' {
>   interface Context {
>     $recaptcha: ReCaptchaInstance
>   }
> }
> ```

**Comment by Arias-xss** [comment]
Why do you use it with `wrapProperty`

Here an example

`const useRecaptcha = wrapProperty('$recaptcha', false)`

`const recaptcha = useRecaptcha()`

And then call the functions.

**Comment by maemaemae3** [comment]
Thanks a lot for replies.
I'm not using this module for a long time, and there is already a workaround like I showed, so let me close this issue for now.
