### ISSUE TITLE
ERROR for site owner: Invalid key type

### ISSUE THREAD

**Issue by gianpesto** [nuxt-community/recaptcha-module#94]
hi i tested both v2 and v3 (using the right keys for each of them) but i keep on getting 
"ERROR for site owner: Invalid key type" on v3 using your v3 example.

nuxt.config.js
```modules: [
[
  '@nuxtjs/recaptcha',
    {
      hideBadge: true,
      version: 3,
      siteKey: process.env.RECAPTCHA_SITE_KEY,
    },
  ],
]
```
component
```
async mounted() {
    try {
      await this.$recaptcha.init()
    } catch (e) {
      console.error(e)
    }
  },
```

the key is correctly inserted into the dom, also the script from recaptcha.net is available, am i missing something?

**Comment by gianpesto** [comment]
So, for anyone having trouble reading this carefully before opening an isssue: 
v3 doesnt need a `<recaptcha/>` because it's tracking your journey on the website and can tell if you're a bot or not.

so just ignore me 😂

**Comment by beshur** [comment]
> v3 doesnt need a because

doesn't need a "what"? a <recaptcha /> element?

**Comment by gianpesto** [comment]
yes, a recaptcha tag

**Comment by beshur** [comment]
well, I've removed the tag, and the script is still downloaded with ?render=SITE_KEY&render=SITE_KEY with a 400 Bad Request
